# define the servers
servers=[
  {
    :hostname => "node-app",
    :memoryram => 512,
    :cpunumber => 2,
    :internal_ip => "10.0.50.10"
  },
]

# initialize vms and configure
Vagrant.configure(2) do |config|
  config.vm.synced_folder '.', '/vagrant', disabled: true
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = "helloproject-centos"
      node.vm.hostname = machine[:hostname]
      node.ssh.username = "helloproject"
      node.ssh.private_key_path = "../files/helloproject_key"
      node.vm.network "private_network", ip: machine[:internal_ip]
      node.vm.provider "virtualbox" do |v|
        v.memory = machine[:memoryram]
        v.cpus = machine[:cpunumber]
      end
      node.vm.provider "vmware_desktop" do |v|
        v.vmx["memsize"] = machine[:memoryram]
        v.vmx["numvcpus"] = machine[:cpunumber]
      end
      config.vm.provision "ansible" do |ansible|
        ansible.verbose = "vv"
        ansible.playbook = "../playbooks/node_deploy.yaml"
        ansible.extra_vars = {
          server_type: "node"
        }
      end
    end
  end
end
