---
- name: set variables
  set_fact:
    puppet_repo_rpm: "https://yum.puppet.com/puppet6/puppet6-release-el-7.noarch.rpm"
    puppet_server_pkg: "puppetserver"
    puppet_agent_pkg: "puppet-agent"
    puppet_service: "puppetserver"
    
- name: add dns in hosts
  lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ puppet_server }}\tpuppet.linx.com"
  when: server_type != "puppet"

- name: add keys puppetlabs
  rpm_key:
    key: https://yum.puppetlabs.com/RPM-GPG-KEY-puppetlabs
    state: present

- name: add repository puppetlabs
  package:
    name: "{{ puppet_repo_rpm }}"
    state: present

- name: install puppetserver
  package:
    name: "{{ puppet_server_pkg }}"
    state: present
  when: server_type == "puppet"

- name: install only puppet agent
  package:
    name: "{{ puppet_agent_pkg }}"
    state: present
  when: server_type != "puppet"

- name: enabled pupper service in server
  service:
    name: "{{ puppet_service }}"
    state: started
    enabled: yes
  when: server_type == "puppet"

- name: enable puppet agent
  command: puppet agent --enable
  when: server_type != "puppet"

- name: ensure binaries puppet in variable PATH
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^Defaults[ |\t]+secure_path ?= ?[a-z/:]+"
    line: "Defaults\tsecure_path = /sbin:/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin/"
    validate: '/usr/sbin/visudo -c -f %s'

- name: copy puppet.conf for agent
  copy:
    src: files/puppet_agent.conf
    dest: /etc/puppetlabs/puppet/puppet.conf
    owner: root
    group: root
    mode: '0644'
  when: server_type != "puppet"